import {
  ModelQuota,
  DeviceSession,
  NanoBananaImage,
  VeoVideoJob,
  CategorizedChat,
  CloudStorageFile,
  GoogleSubscriptionInfo,
} from "@/types";

export const initialGoogleSubscription: GoogleSubscriptionInfo = {
  accountEmail: "developer.admin@gmail.com",
  displayName: "Antigravity Power User",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&h=200&q=80",
  tierName: "Google One AI Premium",
  renewalDate: "2026-09-28",
  storageUsedGb: 48.6,
  storageLimitGb: 2048.0,
  cloudFlareR2Status: "connected",
  r2BucketName: "antigravity-vault-us-east",
  totalSyncedFiles: 1428,
  totalSyncedVolumeGb: 12.4,
};

export const initialQuotas: ModelQuota[] = [
  {
    id: "g3fm",
    name: "Gemini 3 Flash Thinking (G3FM)",
    code: "G3FM-HIGH-THINK",
    category: "LLM",
    remainingPercentage: 15, // The exact user question baseline!
    totalLimit: "1,000,000 Tokens / 5-Hr Window",
    consumed: "850,000 Tokens",
    unit: "Tokens",
    rpmLimit: 150,
    currentRpm: 12,
    tpmLimit: 200000,
    currentTpm: 18400,
    rollingWindowHours: 5,
    nextReplenishMinutes: 28, // Time to next rolling bucket release
    resetMode: "rolling",
    status: "critical",
    hourlyHistory: [
      { hour: "12:00", tokens: 45000, requests: 18 },
      { hour: "13:00", tokens: 120000, requests: 42 },
      { hour: "14:00", tokens: 280000, requests: 95 },
      { hour: "15:00", tokens: 240000, requests: 88 },
      { hour: "16:00", tokens: 110000, requests: 34 },
      { hour: "17:00", tokens: 55000, requests: 14 },
    ],
  },
  {
    id: "gemini-3-pro",
    name: "Gemini 3.0 Pro (Full Reasoning)",
    code: "GEMINI-3.0-PRO",
    category: "LLM",
    remainingPercentage: 82,
    totalLimit: "500,000 Tokens / Day",
    consumed: "90,000 Tokens",
    unit: "Tokens",
    rpmLimit: 60,
    currentRpm: 4,
    tpmLimit: 100000,
    currentTpm: 4200,
    rollingWindowHours: 24,
    nextReplenishMinutes: 380,
    resetMode: "daily_utc",
    status: "optimal",
    hourlyHistory: [
      { hour: "12:00", tokens: 8000, requests: 2 },
      { hour: "13:00", tokens: 15000, requests: 5 },
      { hour: "14:00", tokens: 32000, requests: 11 },
      { hour: "15:00", tokens: 20000, requests: 7 },
      { hour: "16:00", tokens: 10000, requests: 3 },
      { hour: "17:00", tokens: 5000, requests: 1 },
    ],
  },
  {
    id: "claude-37-sonnet",
    name: "Claude 3.7 Sonnet (Hybrid Reasoner)",
    code: "CLAUDE-3.7-SONNET",
    category: "LLM",
    remainingPercentage: 64,
    totalLimit: "250,000 Tokens / 5-Hr Window",
    consumed: "90,000 Tokens",
    unit: "Tokens",
    rpmLimit: 50,
    currentRpm: 0,
    tpmLimit: 50000,
    currentTpm: 0,
    rollingWindowHours: 5,
    nextReplenishMinutes: 94,
    resetMode: "rolling",
    status: "warning",
    hourlyHistory: [
      { hour: "12:00", tokens: 12000, requests: 4 },
      { hour: "13:00", tokens: 40000, requests: 15 },
      { hour: "14:00", tokens: 25000, requests: 9 },
      { hour: "15:00", tokens: 10000, requests: 3 },
      { hour: "16:00", tokens: 3000, requests: 1 },
      { hour: "17:00", tokens: 0, requests: 0 },
    ],
  },
  {
    id: "nano-banana-img",
    name: "Nano-Banana Image Studio",
    code: "NANO-BANANA-DIFFUSION",
    category: "Image",
    remainingPercentage: 85,
    totalLimit: "100 High-Res Renders / Day",
    consumed: "15 Renders",
    unit: "Generations",
    rpmLimit: 10,
    currentRpm: 1,
    tpmLimit: 0,
    currentTpm: 0,
    rollingWindowHours: 24,
    nextReplenishMinutes: 420,
    resetMode: "daily_utc",
    status: "optimal",
    hourlyHistory: [
      { hour: "12:00", tokens: 2, requests: 2 },
      { hour: "13:00", tokens: 5, requests: 5 },
      { hour: "14:00", tokens: 4, requests: 4 },
      { hour: "15:00", tokens: 3, requests: 3 },
      { hour: "16:00", tokens: 1, requests: 1 },
      { hour: "17:00", tokens: 0, requests: 0 },
    ],
  },
  {
    id: "veo-flow-video",
    name: "Google Veo 2 & Flow Labs",
    code: "VEO-2-FLOW-CINEMA",
    category: "Video",
    remainingPercentage: 70,
    totalLimit: "20 Cinematic Video Renders / Day",
    consumed: "6 Renders",
    unit: "Video Clips",
    rpmLimit: 2,
    currentRpm: 0,
    tpmLimit: 0,
    currentTpm: 0,
    rollingWindowHours: 24,
    nextReplenishMinutes: 510,
    resetMode: "daily_utc",
    status: "optimal",
    hourlyHistory: [
      { hour: "12:00", tokens: 1, requests: 1 },
      { hour: "13:00", tokens: 2, requests: 2 },
      { hour: "14:00", tokens: 2, requests: 2 },
      { hour: "15:00", tokens: 1, requests: 1 },
      { hour: "16:00", tokens: 0, requests: 0 },
      { hour: "17:00", tokens: 0, requests: 0 },
    ],
  },
];

export const initialDevices: DeviceSession[] = [
  {
    id: "dev-win-01",
    name: "Windows Studio Workstation (Primary)",
    type: "desktop",
    os: "Windows 11 Pro 64-bit",
    clientVersion: "Antigravity IDE v2.4.1",
    location: "Mumbai, India (Local)",
    ipAddress: "103.141.52.88",
    isCurrent: true,
    status: "online",
    lastActive: "Active Now",
    tokensConsumedToday: 620000,
    imagesGeneratedToday: 8,
    videosRenderedToday: 3,
    activeDaemons: [
      { name: "antigravity-lsp-worker", pid: 2712, runtime: "42m 18s" },
      { name: "r2-sync-agent", pid: 5512, runtime: "41m 55s" },
    ],
  },
  {
    id: "dev-mac-02",
    name: "MacBook Pro M3 Max (Dev Laptop)",
    type: "laptop",
    os: "macOS Sonoma 14.5",
    clientVersion: "Antigravity CLI agy v2.4.0",
    location: "Bengaluru, India",
    ipAddress: "49.207.180.12",
    isCurrent: false,
    status: "idle",
    lastActive: "3 hours ago",
    tokensConsumedToday: 180000,
    imagesGeneratedToday: 4,
    videosRenderedToday: 2,
    activeDaemons: [
      { name: "agy-daemon-service", pid: 18420, runtime: "3h 12m" },
    ],
  },
  {
    id: "dev-s21-03",
    name: "Samsung Galaxy S21+ 5G",
    type: "mobile",
    os: "Android 15 (One UI 7.0)",
    clientVersion: "Antigravity Mobile Mirror Link",
    location: "Mumbai, India",
    ipAddress: "192.168.1.104 (Local ADB)",
    isCurrent: false,
    status: "online",
    lastActive: "Yesterday at 6:13 PM",
    tokensConsumedToday: 45000,
    imagesGeneratedToday: 3,
    videosRenderedToday: 1,
    activeDaemons: [
      { name: "scrcpy-wireless-mirror", pid: 11024, runtime: "Standby" },
    ],
  },
  {
    id: "dev-linux-04",
    name: "Cloud Build Cluster Node #3",
    type: "server",
    os: "Ubuntu 24.04 LTS",
    clientVersion: "Antigravity Headless Runner v2.4.1",
    location: "Frankfurt, Germany",
    ipAddress: "142.250.180.206",
    isCurrent: false,
    status: "offline",
    lastActive: "18 hours ago",
    tokensConsumedToday: 95000,
    imagesGeneratedToday: 0,
    videosRenderedToday: 0,
    activeDaemons: [],
  },
];

export const initialNanoImages: NanoBananaImage[] = [
  {
    id: "img-001",
    title: "Cyberpunk Holographic Interface",
    prompt: "Futuristic dark holographic telemetry dashboard with glowing cyan and neon purple neon graphs, glassmorphism UI, 8k cinematic lighting, ultra-realistic",
    model: "Nano-Banana-v2",
    aspectRatio: "16:9",
    resolution: "3840x2160 (4K UHD)",
    seed: 84920412,
    createdAt: "2026-09-03 14:22",
    deviceId: "dev-win-01",
    deviceName: "Windows Studio Workstation",
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
    creditsUsed: 1,
    tags: ["UI", "Cyberpunk", "Telemetry", "Glassmorphism"],
  },
  {
    id: "img-002",
    title: "Quantum Neural Core Visualization",
    prompt: "Glowing golden and sapphire neural network cortex suspended in deep void, hyper-detailed particle simulation, volumetric lighting, unreal engine 5 render",
    model: "Imagen 3 Ultra",
    aspectRatio: "1:1",
    resolution: "2048x2048",
    seed: 39102455,
    createdAt: "2026-09-03 15:45",
    deviceId: "dev-mac-02",
    deviceName: "MacBook Pro M3 Max",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    creditsUsed: 1,
    tags: ["AI", "Neural", "Particles", "Abstract"],
  },
  {
    id: "img-003",
    title: "Minimalist Architectural Studio Space",
    prompt: "Minimalist concrete creative studio overlooking Tokyo skyline at dusk, warm ambient lighting, architectural photography, Hasselblad 50mm",
    model: "Nano-Banana Fast",
    aspectRatio: "16:9",
    resolution: "1920x1080",
    seed: 71209384,
    createdAt: "2026-09-03 16:10",
    deviceId: "dev-win-01",
    deviceName: "Windows Studio Workstation",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    creditsUsed: 1,
    tags: ["Architecture", "Studio", "Photography", "Interior"],
  },
  {
    id: "img-004",
    title: "Bioluminescent Deep Sea Ecosystem",
    prompt: "Macro underwater shot of iridescent jellyfish drifting through crystal clear trench, glowing blue bioluminescence, National Geographic cinematic depth of field",
    model: "Nano-Banana-v2",
    aspectRatio: "9:16",
    resolution: "1080x1920 (Mobile)",
    seed: 92830114,
    createdAt: "2026-09-02 21:18",
    deviceId: "dev-s21-03",
    deviceName: "Samsung Galaxy S21+ 5G",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
    creditsUsed: 1,
    tags: ["Nature", "Bioluminescence", "Underwater", "Vertical"],
  },
];

export const initialVeoVideos: VeoVideoJob[] = [
  {
    id: "vid-001",
    title: "Futuristic Drone Flying over Neo-Kyoto",
    prompt: "FPV cinematic drone camera diving through rain-slicked neon skyscrapers in Neo-Kyoto at midnight, reflections on wet asphalt, anamorphic lens flare, 60fps",
    engine: "Google Veo 2",
    status: "completed",
    progressPercentage: 100,
    durationSeconds: 12,
    fps: 60,
    aspectRatio: "16:9",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=80",
    createdAt: "2026-09-03 13:10",
    deviceId: "dev-win-01",
    deviceName: "Windows Studio Workstation",
    creditsCost: 2,
  },
  {
    id: "vid-002",
    title: "Flow Labs: Molten Liquid Gold Metamorphosis",
    prompt: "Slow motion macro capture of swirling liquid chrome transforming into incandescent molten gold, cinematic lighting, studio backdrop, 4K rendering",
    engine: "Flow Labs Cinematic",
    status: "completed",
    progressPercentage: 100,
    durationSeconds: 8,
    fps: 60,
    aspectRatio: "16:9",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    createdAt: "2026-09-03 15:30",
    deviceId: "dev-mac-02",
    deviceName: "MacBook Pro M3 Max",
    creditsCost: 2,
  },
  {
    id: "vid-003",
    title: "Deep Space Nebula Hyperdrive Jump",
    prompt: "Cockpit point of view looking out through spaceship viewport as starfield warps into streaking hyperspace light tunnel, nebula dust particles",
    engine: "Google Veo 2",
    status: "rendering",
    progressPercentage: 68,
    durationSeconds: 10,
    fps: 30,
    aspectRatio: "21:9",
    videoUrl: "",
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    createdAt: "2026-09-03 17:05",
    deviceId: "dev-win-01",
    deviceName: "Windows Studio Workstation",
    creditsCost: 2,
  },
];

export const initialChats: CategorizedChat[] = [
  {
    id: "chat-001",
    title: "Antigravity Quota Meter & Cloud Command Center",
    category: "coding",
    modelUsed: "Gemini 3.7 Flash (High)",
    deviceId: "dev-win-01",
    deviceName: "Windows Studio Workstation",
    createdAt: "2026-09-03 17:09",
    updatedAt: "2026-09-03 17:32",
    totalTurns: 18,
    totalTokens: 142800,
    previewMessage: "Verified zero overnight local task execution and scaffolding Next.js Cloud Dashboard with Cloudflare R2 backup.",
    isSyncedToR2: true,
    messages: [
      {
        role: "user",
        timestamp: "17:09",
        content: "last night i hadnt used the antigravity nor my other login session used them >> then how come in the morning i had 15% left of G3FM in agq meter",
      },
      {
        role: "assistant",
        timestamp: "17:09",
        content: "Explained rolling rate limit windows, UTC server boundaries, and account-level shared quota pools.",
        thought: "Analyzing server-side token replenishment mechanics vs local background activity.",
        toolCalls: [
          { tool: "antigravity_guide", summary: "Loaded Antigravity surface specifications" },
        ],
      },
      {
        role: "user",
        timestamp: "17:11",
        content: "could you please verify all these",
      },
      {
        role: "assistant",
        timestamp: "17:12",
        content: "Inspected event logs and confirmed clean shutdown yesterday at 6:13 PM with zero rogue overnight processes.",
        toolCalls: [
          { tool: "run_command", summary: "Executed deep_check.ps1 and verified system sleep timestamps" },
        ],
      },
    ],
  },
  {
    id: "chat-002",
    title: "Samsung Galaxy S21+ ADB Live Mirroring",
    category: "coding",
    modelUsed: "Gemini 3 Flash Thinking",
    deviceId: "dev-s21-03",
    deviceName: "Samsung Galaxy S21+ 5G",
    createdAt: "2026-09-02 17:58",
    updatedAt: "2026-09-02 18:13",
    totalTurns: 28,
    totalTokens: 210000,
    previewMessage: "Configured scrcpy USB debugging mirror, captured live screen screenshot, and cleanly terminated with 'stop everything'.",
    isSyncedToR2: true,
    messages: [
      {
        role: "user",
        timestamp: "18:10",
        content: "Take a screenshot of the connected phone",
      },
      {
        role: "assistant",
        timestamp: "18:10",
        content: "Captured current phone screen and saved artifact to local directory.",
        artifacts: [{ name: "current_phone_screen.png", type: "image/png" }],
      },
      {
        role: "user",
        timestamp: "18:13",
        content: "stop everything",
      },
      {
        role: "assistant",
        timestamp: "18:13",
        content: "Terminated background task-112 and killed all adb / scrcpy processes cleanly.",
      },
    ],
  },
  {
    id: "chat-003",
    title: "Nano-Banana Cyberpunk Visual Concept Studio",
    category: "image-gen",
    modelUsed: "Nano-Banana-v2 / Imagen 3",
    deviceId: "dev-win-01",
    deviceName: "Windows Studio Workstation",
    createdAt: "2026-09-03 14:15",
    updatedAt: "2026-09-03 14:40",
    totalTurns: 12,
    totalTokens: 82000,
    previewMessage: "Generated 4K holographic UI concept mockups and synced prompt seeds to Cloudflare R2 gallery.",
    isSyncedToR2: true,
    messages: [
      {
        role: "user",
        timestamp: "14:15",
        content: "Generate a futuristic cyberpunk holographic UI telemetry dashboard in 16:9 4K with dark glassmorphism",
      },
      {
        role: "assistant",
        timestamp: "14:22",
        content: "Generated image asset with seed 84920412 and saved high-resolution render.",
        artifacts: [{ name: "cyberpunk_ui_concept.png", type: "image/png" }],
      },
    ],
  },
  {
    id: "chat-004",
    title: "Google Veo 2 & Flow Labs Drone Shot Render",
    category: "video-gen",
    modelUsed: "Google Veo 2 Cinematic",
    deviceId: "dev-mac-02",
    deviceName: "MacBook Pro M3 Max",
    createdAt: "2026-09-03 13:00",
    updatedAt: "2026-09-03 13:18",
    totalTurns: 8,
    totalTokens: 64000,
    previewMessage: "Rendered 60fps drone shot flying over Neo-Kyoto in 16:9 with motion vector stabilization.",
    isSyncedToR2: true,
    messages: [
      {
        role: "user",
        timestamp: "13:00",
        content: "Render an FPV drone shot flying between neon skyscrapers in rainy cyberpunk city at 60fps",
      },
      {
        role: "assistant",
        timestamp: "13:10",
        content: "Render completed successfully in 10 minutes. Video uploaded to R2 vault.",
        artifacts: [{ name: "neo_kyoto_drone_60fps.mp4", type: "video/mp4" }],
      },
    ],
  },
  {
    id: "chat-005",
    title: "AlphaFold 3 Protein Structure Analysis",
    category: "science",
    modelUsed: "Gemini 3.0 Pro",
    deviceId: "dev-linux-04",
    deviceName: "Cloud Build Cluster Node",
    createdAt: "2026-09-02 11:20",
    updatedAt: "2026-09-02 12:45",
    totalTurns: 16,
    totalTokens: 118000,
    previewMessage: "Fetched UniProt pLDDT confidence scores and rendered PyMOL active binding site visual.",
    isSyncedToR2: false,
    messages: [
      {
        role: "user",
        timestamp: "11:20",
        content: "Analyze structural confidence metrics for kinase target P00533",
      },
      {
        role: "assistant",
        timestamp: "11:22",
        content: "Calculated pLDDT domain boundaries and exported PyMOL session script.",
      },
    ],
  },
];

export const initialR2Files: CloudStorageFile[] = [
  {
    id: "r2-001",
    name: "transcript_current_session.jsonl",
    path: "/synced-chats/transcript.jsonl",
    type: "file",
    category: "chat_logs",
    sizeBytes: 76789,
    lastModified: "2026-09-03 17:32",
    syncStatus: "synced",
    r2Etag: '"9a7f8b912c01"',
    deviceId: "dev-win-01",
  },
  {
    id: "r2-002",
    name: "session-e1528e1e.jsonl",
    path: "/synced-chats/session-e1528e1e.jsonl",
    type: "file",
    category: "chat_logs",
    sizeBytes: 121895,
    lastModified: "2026-09-02 18:13",
    syncStatus: "synced",
    r2Etag: '"3c84f102ba5e"',
    deviceId: "dev-s21-03",
  },
  {
    id: "r2-003",
    name: "cyberpunk_ui_4k_render.png",
    path: "/nano-banana-gallery/cyberpunk_ui_4k_render.png",
    type: "file",
    category: "images",
    sizeBytes: 4892010,
    lastModified: "2026-09-03 14:22",
    syncStatus: "synced",
    r2Etag: '"e14890ac38b2"',
    deviceId: "dev-win-01",
  },
  {
    id: "r2-004",
    name: "neo_kyoto_drone_60fps.mp4",
    path: "/veo-videos/neo_kyoto_drone_60fps.mp4",
    type: "file",
    category: "videos",
    sizeBytes: 38402910,
    lastModified: "2026-09-03 13:10",
    syncStatus: "synced",
    r2Etag: '"bf8923d047a1"',
    deviceId: "dev-win-01",
  },
  {
    id: "r2-005",
    name: "antigravity_workspace_state.tar.gz",
    path: "/workspaces/antigravity_workspace_state.tar.gz",
    type: "file",
    category: "workspaces",
    sizeBytes: 15829100,
    lastModified: "2026-09-03 17:30",
    syncStatus: "syncing",
    r2Etag: '"pending-delta"',
    deviceId: "dev-win-01",
  },
  {
    id: "r2-006",
    name: "google_subscription_telemetry.json",
    path: "/configs/google_subscription_telemetry.json",
    type: "file",
    category: "configs",
    sizeBytes: 14200,
    lastModified: "2026-09-03 17:31",
    syncStatus: "synced",
    r2Etag: '"11840ba9ef30"',
    deviceId: "dev-win-01",
  },
];
